#define NUL "\0"
#define SOH "\x01"
#define STX "\x02"
#define ETX "\x03"
#define EOT "\x04"
#define ENQ "\x05"
#define ACK "\x06"
#define BEL "\x07"
#define BS  "\x08"
#define TAB "\x09"
#define LF  "\x0A"
#define VT  "\x0B"
#define FF  "\x0C"
#define CR  "\x0D"
#define SO  "\x0E"
#define SI  "\x0F"
#define DLE "\x10"
#define DC1 "\x11"
#define DC2 "\x12"
#define DC3 "\x13"
#define DC4 "\x14"
#define NAK "\x15"
#define SYN "\x16"
#define ETB "\x17"
#define CAN "\x18"
#define EM  "\x19"
#define SUB "\x1A"
#define ESC "\x1B"
#define FS  "\x1C"
#define GS  "\x1D"
#define RS  "\x1E"
#define US  "\x1F"
#define DEL "\x7F"

#define FNC1 "È"
#define FNC2 "É"
#define FNC3 "Ë"
#define FNC4 "Ê"

#define SHIFT "ô"
#define START_A "õ"
#define START_B "ö"
#define START_C "ø"

#define CODE_A "ù"
#define CODE_B "ú"
#define CODE_C "û"

#define STOP "ü"

#define ON "\xFF"
#define OFF "\x00"